# Generated by Django 4.1.5 on 2023-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project_name',
        ),
        migrations.AddField(
            model_name='client',
            name='project_name',
            field=models.ManyToManyField(to='api.project'),
        ),
    ]
